[project]
authors = ["RyanLeber <ryanleber1@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "mojo-ecs-nightly"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0.dev2024120105,<25"
sdl2 = ">=2.30.7,<3"
sdl2_gfx = ">=1.0.4,<2"
sdl2_image = ">=2.8.2,<3"

